version: "3"
services: 
  gestion:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: elDeSant14g0
    ports:
      - 33308:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8182:8080