version: "3"
services: 
  gestion:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - ${ADMINER_PORT}:8080
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d