version: '3.1'

services: 
  db-stack:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: elDeSant14g0
      MYSQL_DATABASE: libros judas tadeo
    ports:
      - "33308:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - "8183:8080"