version: "3"
services: 
  db-stack:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
<<<<<<< HEAD
      - ${ADMINER_PORT}:8080
=======
      - ${ADMINER_PORT}:8080
>>>>>>> abb050b8485da9867aa7f1c4794eada177ce59e1
